config/routes.rb
Rails.application.routes.draw do
  # get 'reviews/index'
  # get 'reviews/create'
  # get 'reviews/new'
  # # get 'play_dates/create'
  # # get 'play_dates/index'
  # get 'pets/index'
  # get 'pets/new'
  # get 'pets/create'
  # get 'pets/show'
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :pets do
    resources :play_dates
  end
  resources :play_dates do
    resources :reviews, only: [:create, :new]
  end
  resources :user do
    resources :play_dates
      # resources :reviews, only: [:create, :new]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/pet.rb
class Pet < ApplicationRecord
  # validate :available?

  belongs_to :user
  has_many :play_dates, dependent: :destroy
  has_many :reviews, through: :play_dates
  has_one_attached :photo

  validates :name, presence: true
  validates :breed, presence: true
  validates :pet_type, presence: true
  validates :bio, presence: true
  # validates :photo, presence: true

  def average
    array = reviews.pluck(:rating)
    return 0 if array.empty?

    # return format('%.1f', (array.sum / array.size)).to_i
    return array.sum / array.size
  end

  include PgSearch::Model
  pg_search_scope :pet_search,
                  against: %i[name pet_type bio],
                  associated_against: {
                    user: %i[first_name last_name]
                  },
                  using: {
                    tsearch: { prefix: true }
                  }
end

app/models/play_date.rb
class PlayDate < ApplicationRecord
  # validate :available

  belongs_to :user
  belongs_to :pet

  has_one :review, dependent: :destroy

  validates :start_time, :end_time, presence: true
  validates :start_time, :end_time, uniqueness: true

  include PgSearch::Model
  pg_search_scope :playdate_search,
                  against: %i[start_time end_time],
                  associated_against: {
                    pet: %i[name bio pet_type user_id]
                  },
                  using: {
                    tsearch: { prefix: true }
                  }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :play_date

  validates :rating, presence: true
  validates :rating, acceptance: { accept: [0, 1, 2, 3, 4, 5] }
  validates :rating, numericality: { only_integer: true }
  validates :play_date, uniqueness: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :play_dates
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[phone_number])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update,
                                      keys: %i[phone_number])
  end
end

#nothing to see here

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
  end
end

app/controllers/pets_controller.rb
class PetsController < ApplicationController
  # skip_before_action :authenticate_user!, only: :home

  def index
    @user = current_user
    @play_dates = current_user.play_dates
    if params[:query].present?
      @pets = Pet.all.pet_search(params[:query])
    else
      @pets = Pet.all
    end
  end

  def new
    @pet = Pet.new
  end

  def edit
    @user = current_user
    @pet = Pet.find(params[:id])
    return unless @pet[:user_id] != @user[:id]

    redirect_to pet_path(@pet)
  end

  def create
    @user = current_user
    @pet = Pet.new(pet_params)
    @pet.user = @user
    if @pet.save
      redirect_to pet_path(@pet)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @pet = Pet.find(params[:id])
    @play_dates = current_user.play_dates.where(pet: @pet)
    @user = current_user
    @play_date = PlayDate.new
    @reviews = Review.all
  end

  private

  def pet_params
    params.require(:pet).permit(:pet_type, :name, :breed, :bio, :photo)
  end
end

app/controllers/play_dates_controller.rb
class PlayDatesController < ApplicationController
  before_action :find_pet, only: [:create, :new]
  # before_action :find_review, only: [:index]

  def new
    @play_date = PlayDate.new
  end

  def create
    @user = current_user
    @all_play_dates = PlayDate.all
    @play_date = PlayDate.new(play_date_params)
    @play_date.user = @user
    @play_date.pet = @pet


    @start_time = @play_date.start_time
    @end_time = @play_date.end_time
    found = false

    @all_play_dates.each do |date|
      starts = date.start_time
      ends = date.end_time
      if @start_time.between?(starts, ends) || @end_time.between?(starts, ends)
        if date.pet_id == @play_date.pet_id
          found = true
        end
      end
    end

    if found == true
      redirect_to pet_path(@pet), notice: "Sorry this pet is booked between these times"
    else
      @play_date.save
      redirect_to pet_path(@pet)
    end
  end

  def index
    @play_dates = current_user.play_dates
    if params[:query].present?
      @play_dates = current_user.play_dates.playdate_search(params[:query])
    else
      @play_dates = current_user.play_dates
    end
  end

  def edit
    # @user = current_user
    @play_date = PlayDate.find(params[:id])
    # return unless @play_date[:user_id] != @user[:id]

    # redirect_to pet_path(@play_date[:pet_id])
  end

  def update
    @play_date = PlayDate.find(params[:id])
    @play_date.update(play_date_params)
    @play_date.save
    redirect_to pet_path(@play_date[:pet_id])
  end

  def destroy
    @play_date = PlayDate.find(params[:id])
    @play_date.destroy
    redirect_to play_dates_path
  end

  private

  def play_date_params
    params.require(:play_date).permit(:start_time, :end_time)
  end

  def find_pet
    @pet = Pet.find(params[:pet_id])
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :find_play_date, only: [:create, :new]

  def index
    @reviews = Review.all
    # @play_dates = PlayDate.all
    @user = current_user
    @reviews.select(params[:user_id].to_i)
  end

  def create
    @user = current_user
    @review = Review.new(review_params)
    @review.play_date_id = @play_date.id
    # play_dates = PlayDate.all
    # filters = play_dates.select { |date| date.user == @user }
    # # filters.each do |filter|
    # #   filter.id != @review.play_date_id
    # # end
    # raise
    if @review.save
      redirect_to pet_path(@play_date[:pet_id])
    else
      # render :new, status: :unprocessable_entity
      redirect_to pet_path(@play_date[:pet_id])
    end
  end

  def new
    @review = Review.new
  end

  private

  def review_params
    params.require(:review).permit(:rating, :content)
  end

  def find_play_date
    @play_date = PlayDate.find(params[:play_date_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
  <html>
    <head>
      <title>BorrAPet!</title>
      <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
      <%= csrf_meta_tags %>
      <%= csp_meta_tag %>

      <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
      <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: false %>

      <p class="notice mb-0"><%= notice %></p>
      <p class="alert mb-0"><%= alert %></p>
    </head>
    <body>
      <div class="home-container">
        <% unless params[:action] == "home" %>
          <div class="container mb-5">
        <% end %>

        <%# Navbar %>
          <%= render '/shared/navbar' %>
          <%= yield %>
        <% unless params[:action] == "home" %>
          </div>
        <% end %>
        <%= render '/shared/footer' %>
      </div>
    </body>
  </html>

app/views/pages/home.html.erb
<div class="banner w-100" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(<%= asset_path 'banner.jpg' %>); margin-top: -30px;">

  <div class="container">
    <div class="text-flex">
      <h1 class="fs-1"> Welcome to <strong>BorrAPet</strong>!</h1>
      <p class="fs-4">If you're a busy professional or someone that loves animals but don't have your own, BorrAPet is the platform for you!</p>
      <div class="index-button"><%= link_to "View all pets", pets_path %></div>
    </div>
  </div>
</div>

<section class="about" id="about">
  <div class="container">
    <div class="headline">
      <h2 class="fs-1">About BorrAPet</h2>
      <p class="sub-text fs-5">We are passionate about helping animal lovers connect with all kinds of pets, including those that are no longer with us. We understand that pets are more than just animals; they are beloved members of our families. Our app provides a platform for individuals who are interested in borrowing animals from a wide range of species, including dinosaurs and many other extinct animals.</p>
    </div>
    <div class="content">
      <div class="text-container-flex">
        <div class="item">
          <div class="description">
            <h3 class="fs-2">BorrAPet is for everyone</h3>
            <p class="fs-5">Our platform connects pet owners with individuals who are interested in borrowing their beloved pets for a short period of time.</p>
          </div>
        </div>
        <div class="item">
          <div class="description">
            <h3 class="fs-2">BorrAPet's mission</h3>
            <p class="fs-5">We strive to create a safe, reliable, and fun way for people to connect with pets and their owners.</p>
          </div>
        </div>
        <div class="item">
          <div class="description">
            <h3 class="fs-2">And for every pet</h3>
            <p class="fs-5">From friendly dinosaurs to majestic mammoths, our app offers a variety of options to suit your needs and interests.</p>
          </div>
        </div>
        <div class="item">
          <div class="description">
            <h3 class="fs-2">Share your love of pets</h3>
            <p class="fs-5">We believe that sharing the love of pets can enrich lives and create meaningful connections. </p>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>


<section class="reviews" id="reviews">
  <div class="container">
    <div class="headline">
      <h2 class="text-center fs-1">BorrAPet Reviews</h2>
      <p style="color:black;" class="text-center sub-text fs-5">Discover what others are saying: read reviews from our satisfied customers!</p>
    </div>
    <div class="info">
      <div class="item">
        <div class="relative orange">
          <div class="absolute">
            <q class="quote fs-5">This shouldn't even be possible. Show us the science. Where is the science? We need the science.</q>
          </div>
        </div>
        <p class="client" style="color:black;"><span class="name">London Natural History Museum</span></p>
      </div>
      <div class="item">
        <div class="relative green">
          <div class="absolute">
            <q class="quote fs-5">I thought some of these were extinct. This is fiction at this point. Are we in the Disney universe?</q>
          </div>
        </div>
          <p class="client" style="color:black;"><span class="name">The Smithsonian Institution</span></p>
      </div>
      <div class="item">
        <div class="relative orange">
          <div class="absolute">
            <q class="quote fs-5">I've been using this pet borrowing site for over a year now and have had nothing but positive experiences.</q>
          </div>
        </div>
        <p class="client" style="color:black;"><span class="name">John Doe</span></p>
      </div>
      <div class="item">
        <div class="relative green">
          <div class="absolute">
            <q class="quote fs-5">I love BorrAPet! I've borrowed pets from cats to dinosaurs and had great experiences with each one.</q>
          </div>
        </div>
        <p class="client" style="color:black;"><span class="name">Jane Doe</span></p>
      </div>
    </div>
  </div>
</section>

<section class="subscribe" id="subscribe">
  <div class="container subscribe-flex">
    <div class="headline">
      <h2 fs-1">Create an account and have fun with one of our many pets!</h2>
      <p class="sub-text fs-5"">Why not join our BorrAPet community and embark on a journey to discover new and exciting animals? With just a few clicks, you can connect with pet owners in your area and experience the wonder of these magnificent creatures for yourself.</p>
    </div>
    <div class="index-button"><%= link_to "Create account", new_user_registration_path %></div>
  </div>
</section>



<!--
  <div class="container">
    <h1 class="fs-1"> Welcome to <strong>BorrAPet</strong>!</h1>
    <p class="fs-4">If you're a busy professional or someone that loves animals but don't have your own, BorrAPet is the platform for you!</p>
    <div class="index-button"><%= link_to "View all pets", pets_path %></div>
  </div>
-->

app/views/pets/create.html.erb
<h1>Add a new pet</h1>

app/views/pets/index.html.erb
<h1 class="d-flex justify-content-center mb-4">All Pets</h1>
<div class="d-flex justify-content-center">
</div>

<%= form_with url: pets_path, method: :get, class: "d-flex" do %>
  <%= text_field_tag :query,
    params[:query],
    class: "form-control",
    placeholder: "Find a pet"
  %>
  <%= submit_tag "Search", class: "btn btn-primary" %>
<% end %>

<br>

<div class="row">
  <% @pets.each do |pet| %>
    <div class="col-md-3">
      <%= link_to pet_path(pet), class:"text-decoration-none" do %>
        <div class="card mb-3">
        <% if pet.photo.attached? == false %>
          <img src="https://miro.medium.com/max/650/0*zV9kLZ9GyYscLrhX.jpg" class="card-img-top img-fluid" alt="dog">
        <% else %>
          <img src=<%= pet.photo.url %> class="card-img-top img-fluid">
        <% end %>
          <div class="card-body">
            <h3 class="card-title"><%= pet.name %></h3>
            <h5 class="card-location"><%= pet.user.address %></h5>
            <% if pet.average == 0 %>
              <p>No reviews</p>
            <% else %>
              <%= pet.average %>
              <!-- <%= pet.average.times do %>
                <i class="fa-solid fa-star">
              <% end %> -->
            <% end %>
          </div>
        </div>
      <% end %>
    </div>
  <% end %>
</div>

app/views/pets/new.html.erb
<div class="container new-card">
  <h1>Add a new pet</h1>
    <%= simple_form_for(@pet) do |f| %>
      <%= f.input :name %>
      <%= f.input :pet_type %>
      <%= f.input :breed %>
      <%= f.input :bio %>
      <%= f.input :photo, as: :file %>
      <%# <%= f.input :photo, as: :file %>
      <div class="index-button"><%= f.button :submit %></div>
    <% end %>
</div>

app/views/pets/show.html.erb
<div class="show-container">
  <div class="top-a">
    <h1><%= @pet.name %> the <%= @pet.pet_type.capitalize %></h1>
    <p class="fs-6 fw-bold mb-0">Average pet rating</p>
    <p><%= @pet.average.times.map { "⭐" }.join("") %></p>
  </div>

  <div class="show-show d-flex justify-content-start">


    <div class="show-pic">
      <% if @pet.photo.attached? == false %>
        <i class="fa-regular fa-images fa-shake" style="--fa-animation-duration: 2s;"></i>
      <% else %>
        <%= cl_image_tag @pet.photo.key, height: 300, width: 400, crop: :fill %>
      <% end %>
    </div>

    <div class="show-info">
      <p class="fs-6 fw-bold mb-0">About <%= @pet.name %></p>
      <p><%= @pet.bio %></p>

      <p class="fs-6 fw-bold mb-0">Pet Reviews</p>
      <% if @reviews.nil? && @pet.play_dates.where(user: @user) %>
        <p><%= link_to "Be the first to leave a review.", new_play_date_review_path(play_date) %></p>
      <% elsif @pet.play_dates.where(user: @user) %>
        <% @pet.play_dates.each do |play_date| %>
          <% reviews = @reviews.first(3).select { |review| review.play_date_id == play_date[:id] } %>
          <% reviews.each do |review| %>
            <p><%= review.content %></p>
          <% end %>
        <% end %>
      <% elsif @reviews.nil? %>
        <p>No reviews yet.</p>
      <% else %>
        <p><%= link_to "Be the first to leave a review.", new_play_date_review_path(play_date) %></p>
        <% @pet.play_dates.each do |play_date| %>
          <% reviews = @reviews.first(3).select { |review| review.play_date_id == play_date[:id] } %>
          <% reviews.each do |review| %>
            <p><%= review.content %></p>
          <% end %>
        <% end %>
      <% end %>
    </div>
  </div>

  <div class="form-playdates">
    <h4>Book a playdate with <%= @pet.name %>:</h4>
    <%= simple_form_for [@pet, @play_date], data: { controller: 'flatpickr' } do |f| %>
      <%= f.input :start_time, as: :string, input_html: { data: { flatpickr_target: "startTime" } } %>
      <%= f.input :end_time, as: :string, input_html: { data: { flatpickr_target: "endTime" } } %>
      <%= f.submit 'Schedule playdate' %>
    <% end %>
  </div>


  <h2 class="mt-3">Playdates</h2>
  <div class="row">
    <% if @play_dates.present? %>
      <% @play_dates.each do |play_date| %>
        <div class="col-md-3">
          <div class="card border border-secondary-subtle mb-3 mt-3 " style="width: 18rem;">
            <div class="card-body">
              <h5 class="card-title">Your playdate with <%= play_date.pet.name %></h5>
              <p class="card-text"> Starting at: <%= play_date.start_time %></p>
              <p class="card-text"> Finishing at: <%= play_date.end_time %></p>
              <p class="card-text"><%= link_to "Review your play date", new_play_date_review_path(play_date) %></p>
            </div>
          </div>
        </div>
        <% end %>
      <% else %>
        <p>You don't have any playdates with <%= @pet.name %>.</p>
    <% end %>
  </div>
</div>

app/views/play_dates/create.html.erb
<h1>PlayDates#create</h1>

app/views/play_dates/index.html.erb
<h1 style="margin-bottom: 0px;">Your PlayDates</h1>
<br>

<%= form_with url: play_dates_path, method: :get, class: "d-flex" do %>
  <%= text_field_tag :query,
    params[:query],
    class: "form-control",
    placeholder: "Find a playdate"
  %>
  <%= submit_tag "Search", class: "btn btn-primary" %>
<% end %>

<% if @play_dates.nil? %>
  <p>You don't have any playdates...</p>
  <% else %>
  <div class="row">
  <% @play_dates.each do |play_date| %>
    <div class="col-md-3 mb-4">
      <div class="card mb-3 mt-3 w-100 h-100">
      <% if play_date.pet.photo.attached? == false %>
          <img src="https://miro.medium.com/max/650/0*zV9kLZ9GyYscLrhX.jpg" class="card-img-top img-fluid" alt="dog">
        <% else %>
          <img src=<%= play_date.pet.photo.url %> class="card-img-top img-fluid">
        <% end %>
        <div class="card-body">
          <h5 class="card-title">Your playdate with <%= play_date.pet.name %></h5>
        <p class="card-text"> Starting at: <%= play_date.start_time.strftime('%Y-%m-%d') %></p>
          <p class="card-text"> Finishing at: <%= play_date.end_time.strftime('%Y-%m-%d') %></p>
          <p class="card-text rev-button d-flex justify-content-center"><%= link_to "Add Review", new_play_date_review_path(play_date) %></p>
        </div>
      </div>
    </div>
  <% end %>
  </div>
<% end %>
<div class="index-button mt-5"><%= link_to "Back to all pets", pets_path %></div>

app/views/play_dates/new.html.erb
<h1>Add a new play date</h1>
<%= simple_form_for [@pet, @play_date] do |f| %>
  <%= f.input :start_time %>
  <%= f.input :end_time %>
  <%# <%= f.input :photo, as: :file %>
  <%= f.button :submit %>
<% end %>

app/views/reviews/create.html.erb
<h1>Reviews#create</h1>

app/views/reviews/index.html.erb
<h1>Reviews#index</h1>

app/views/reviews/new.html.erb
<h1>Review your playdate</h1>
<%= simple_form_for [@pet, @play_date, @review] do |f| %>
  <%= f.input :rating %>
  <%= f.input :content %>
  <%# <%= f.input :photo, as: :file %>
  <%= f.button :submit %>
<% end %>

app/views/shared/_footer.html.erb
<footer class="footer-container">
  <div class="footer">Made with <span class="green-heart">♥</span> by <a href="https://github.com/LucasNseyep" title="LucasNseyep" class="footer-link">Howling Moon</a></div>
</footer>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon height-3 fixed-top ">
  <div class="container-fluid">
    <%= link_to user_signed_in? ? "/pets" : "/", class: "navbar-brand fw-bolder" do %>
      <div class="dog-container">
        <span class="fa-stack fa-md">
          <i class="fa fa-circle fa-stack-2x"></i>
          <i class="fa fa-dog fa-stack-1x fa-inverse dog-icon"></i>
        </span>
      </div>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <%# Drop Down %>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
        <%# <div> %>
          <li class="nav-items-group" >
            <%= link_to "+", new_pet_path, :class=>"nav-items-list plus", :style=>"text-decoration: none;" %>
            <%= link_to "My PlayDates", "/user/[:id]/play_dates", :class=>"nav-items-list", :style=>"text-decoration: none;" %>
          </li>
          <li class="nav-item dropdown h-100">
            <div class="dropdown-toggle menu-profile h-100" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <img id="avatar" class="avatar dropdown-toggle" src="https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_640.png"/>
              <span class="navbar-toggler-icon"></span>
            </div>
              <div class="dropdown-menu dropdown-menu-end mt-3" aria-labelledby="navbarDropdown">
                <%# <%= link_to "Add Your Pet", new_pet_path, class: "dropdown-item" %>
                <%# <%= link_to "See Your PlayDates", "/user/[:id]/play_dates", class: "dropdown-item" %>
                <%= link_to "View Available Pets", "/pets", class: "dropdown-item" %>
                <%= link_to "Log out", destroy_user_session_path, class: "dropdown-item btn-log-out", data: {turbo_method: :delete} %>
              </div>
          </li>
        <%# </div> %>
        <% else %>
          <li class="nav-item d-flex">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
            <%= link_to "Sign Up", new_user_registration_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>
<div style="height: 105px"></div>